Repository hmcts/hmc-operational-reports-runner, pull requests merged in 2023-10, with the labels that each got.

#92 CCD-4845: renovate config
  .github/renovate.json
Labels: ns:hmc, prd:hmc, rel:hmc-operational-reports-runner-pr-92

#95 CCD-4949:Fix - Versions below java-logging: 6.0.1
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-operational-reports-runner-pr-95

#91 HMAN-566: Adding in error description to reports
  src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingRequestToCsvMapper.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/HearingRequestForCsv.java
  src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingRequestToCsvMapperTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-operational-reports-runner-pr-91
