Repository hmcts/hmc-operational-reports-runner, pull requests merged in 2023-02, with the labels that each got.

#60 HMAN-515 Bump rse-gradle plugin to add dependency-check v8.0.2
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-operational-reports-runner-pr-60

#63 HMAN-508: Fix CVEs in hmc-operational-reports-runner repo
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-operational-reports-runner-pr-63

#58 HMAN-509 Remove discoveryComposite from health endpoint
  src/integrationTest/resources/application-itest.yaml
  src/main/resources/application.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-operational-reports-runner-pr-58

#66 Update 'chart'job' to latest : Chart.yaml
  charts/hmc-operational-reports-runner/Chart.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-operational-reports-runner-pr-66
